book_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('book_logs.urls','book_logs'), namespace='book_logs')),
    path('users/', include(('users.urls','users'),namespace='users'))
]

book_logs/urls.py
from django.urls import path
from book_logs import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topics/<topic_id>/', views.topic, name='topic'),
    path('add_topic', views.add_topic, name='add_topic'),
    path('add_entry/<topic_id>/', views.add_entry, name='add_entry'),
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),
    path('delete_entry/<entry_id>/', views.delete_entry, name='delete_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from users import views


urlpatterns=[
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='/'),name='logout'),
    path('register', views.register, name='register'),
]

book_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    entry = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.entry[:50]+' ...'

users/models.py
from django.db import models

# Create your models here.

book_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title']
        labels = {'title':'Title'}
        help_texts = {
           'title': ('enter your topic here.'),
        }
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['entry']
        labels = {'entry':'EntryText'}
        #help_texts = {
        #    'entry': ('enter your text here.'),
        #}
        widgets = {'entry':forms.Textarea(attrs={'cols': 80, 'rows': 20})}

users/forms.py
from django import forms
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  



class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='username', min_length=5, max_length=150)
    email = forms.EmailField(label='email')  
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)  

    def sanitize_username(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def sanitize_email(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError(" Email Already Exist")  
        return email  
  
    def sanitize_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password2']  
        )  
        return user  

book_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.

def index(request):
    return render(request, 'book_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {'topics':topics}
    return render(request, 'book_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entry = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entry':entry}
    return render(request, 'book_logs/topic.html', context)

@login_required
def add_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('book_logs:topics'))
    context = {'form':form}
    return render(request, 'book_logs/add_topic.html', context)

@login_required
def add_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            return HttpResponseRedirect(reverse('book_logs:topic',args=[topic_id]))
    context = {'form':form, 'topic':topic} 

    return render(request, 'book_logs/add_entry.html', context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('book_logs:topic',args=[topic.id]))
    context = {'form':form,'entry':entry}
    return render(request, 'book_logs/edit_entry.html', context)

def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic_id = entry.topic_id
    entry.delete()
    return HttpResponseRedirect(reverse('book_logs:topic', args=[topic_id]))
    #return #render(request, 'book_logs/topic/.html') because the delete view doesnt need to render or create
    #a new page. theres no need to return render

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = RegisterUserForm()
    else:
        form = RegisterUserForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            auth_user = authenticate(username=new_user.username, email=new_user.email, password=request.POST['password2'])
            if auth_user is not None:
                login(request,auth_user)
                return HttpResponseRedirect(reverse('book_logs:index'))
    context = {'form':form}
    return render(request, 'users/register.html', context)

book_logs/templates/book_logs/add_entry.html
{% extends 'book_logs/base.html' %}
{% load bootstrap5 %}


{% block header %}
<h3>{{topic}}</h3>
{% endblock header %}

{% block content %}

<p class="">Add entry</p>

<form action="{% url 'book_logs:add_entry' topic.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" value="submit">Add Entry</button>
</form>

{% endblock content %}

book_logs/templates/book_logs/add_topic.html
{% extends 'book_logs/base.html' %}
{% load bootstrap5 %}

{% block content %}

<p>Add Topic</p>

<form action="{% url 'book_logs:add_topic' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button value="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
</form>

{% endblock content %}

book_logs/templates/book_logs/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary mb-5">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'book_logs:index' %}">Book Log</a>
          <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'book_logs:topics' %}">Topics</a>
              </li>
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
                <a class="nav-link" href="#">Welcome</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link disabled">{{user}}</a>
                </li>
              
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link disabled">Guest</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
              {% endif %}
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            
          </div>
        </div>
      </nav><!--end-of-nav-->

      <div class="container">
        <div class="page-header">
          {% block header %}
          
          {% endblock header %}
        </div>
        <div>
          {% block content %}
          
          {% endblock content %}
        </div>
      </div>
</body>

</html>

book_logs/templates/book_logs/edit_entry.html
{% extends 'book_logs/base.html' %}
{% load bootstrap5 %}

{% block header %}
<h3>{{entry.topic}}</h3>
{% endblock header %}

{% block content %}

<form action="{% url 'book_logs:edit_entry' entry.id %}" method="POST">
    {% csrf_token%}
    {% bootstrap_form form %}
    <button class="btn btn-primary" value="submit">Submit Changes</button>
</form>

{% endblock content %}

book_logs/templates/book_logs/index.html
{% extends 'book_logs/base.html' %}

{% block header %}
<div class="bg-light text-dark mb-5 mt-5 card p-5 text-center">
    <h1 class="display-4">Welcome to Book Log</h1>
</div>
{% endblock header %}
{% block content %}
<!-- <hr class="my-2"> -->
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h2 class="lead text-center">
                Welcome <strong>{{ user.username }}</strong>
            </h2>
            <h2 class="lead text-center mt-5">
                <a class="btn btn-primary p-3" href="{% url 'book_logs:topics' %}">Access your logs</a>
                
            </h2>
            
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h2 class="lead text-center">
                An application that allows you to save the topics of books you've read. 
                you can make entries about anything you learn easily
            </h2><br>
            <h2 class="lead text-center">
                register an account today to enjoy all that book log has to offer
            </h2>
        </div>
    
        <div class="col-md-12 text-center mt-4">
            <a class="btn btn-primary" href="{% url 'users:register' %}">Register</a>
        </div>
    {% endif %}
    </div>


{% endblock content %}

book_logs/templates/book_logs/topic.html
{% extends 'book_logs/base.html' %}

{% block header %}
<h2>Topic: {{topic}}</h2>
{% endblock header%}

{% block content %}

<p><a href="{% url 'book_logs:add_entry' topic.id %}">Add Entry</a></p>
<ul class="list-unstyled">    
    {% for entry in entry %}
        <li>
            <div class="card d-flex bg-secondary text-white p-3 fs-6" style="border-radius: 5px 5px 0 0;">
                <h5>{{entry.date_added|date:'M d, Y'}}</h5><small class="d-inline">{{entry.date_added|date:'H:i'}}</small>
            </div>
            <div class="card card-body rounded-0 mb-5">
                <p>{{entry.entry|escape|linebreaks}}</p>
            
                <div class="row">
                    <div class="col-sm-3 d-flex justify-content-start" style="gap:10px">
                        <p><a href="{% url 'book_logs:edit_entry' entry.id %}" class="btn btn-primary gx-5">Edit</a></p>
                        <p><a href="{% url 'book_logs:delete_entry' entry.id %}" class="btn btn-danger">Delete</a></p>
                    </div>
                    
                </div>
     
        </div>
        </li>
    
        {% empty %}
        <li>there are entries for this topic yet</li>
        {% endfor %}
      
</ul>

{% endblock content %}

book_logs/templates/book_logs/topics.html
{% extends 'book_logs/base.html' %}

{% block header %}
<h2 class="md-5">Topics</h2>
{% endblock header %}
{% block content %}

    <p class="mt-3">
        <a href="{% url 'book_logs:add_topic' %}">Add Topics</a>
    </p>
    <ul class="list-unstyled">
        {% for topic in topics %}
        <li><h4><a class="text-decoration-none" href="{% url 'book_logs:topic' topic.id %}">{{topic}}</h4></li>
        {% empty %}
        <li>there are no topics available yet</li>
        {% endfor %}
    </ul>
    
{% endblock content %}

users/templates/users/login.html
{% extends 'book_logs/base.html' %}
{% load bootstrap5 %}

{% block header %}
<div class="d-flex align-items-center justify-content-center">
    <h2>Log into your account</h2>
</div>

{% endblock header %}

{% block content %}

    {% if form.errors %}
        <p>Username or password incorrect</p>
    {% endif %}

    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-6">
            <form action="{% url 'users:login' %}" method="POST" class="form mt-5">
                {% csrf_token %}
                {% bootstrap_form form %}
        
                {% buttons %}
                    <button value="submit" class="btn btn-primary">Login</button>
                {% endbuttons %}
                <input type="hidden" name="next" value="{% url 'book_logs:index' %}" />
            </form>
        </div>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends 'book_logs/base.html' %}
{% load bootstrap5 %}


{% block header%}
<h2 class="d-flex align-items-left justify-content-center">Register</h2>
{% endblock %}
{% block content %}


<div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-6">
        <table>
            <form action="{% url 'users:register' %}" method="POST" class="form mt-5">
                {% csrf_token %}
                {% bootstrap_form form %}
        
                {% buttons %}
                    <button value="submit" class="btn btn-primary">Register</button>
                {% endbuttons %}
                <input type="hidden" name="next" value="{% url 'book_logs:index' %}" />
            </form>
        </table>
        
    </div>
</div>


{% endblock content %}